### ISSUE TITLE
Thermocouples

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#12]
Spec out Thermocouple Amps and add them into the PCB design
Should just be an analog input unless we get Thermocouple specific ICs

**Comment by APBashara** [comment]
Controls wants 3 Thermocouple inputs so add 5 at least

**Comment by clairejhaas** [comment]
[K Type Analog Output Amps](https://www.adafruit.com/product/1778)

Are we also speccing the thermocouples too or just the amps? @APBashara

**Comment by APBashara** [comment]
Should be just the Amps. I will double check with Logan. I am pretty sure the Thermocouples they found are built into the brake pads.

**Comment by APBashara** [comment]
All of the Thermocouples will be K type. Controls has yet to pick out the exact ones.

**Comment by APBashara** [comment]
Look into how we can connect Thermocouples
Need to verify that we can solder them into our connectors or consider making a daughter board to add them to our main harness

**Comment by APBashara** [comment]
Looks like the thermocouple connectors are generally recommended as they are specific metals; however, we can solder them. We can look at buying specific wires or getting PCB header connectors for a daughter board. We just need to make sure we have a good plan for mounting any daughter bords we make.

**Comment by APBashara** [comment]
https://digilent.com/shop/thermocouple-wire-k-type/

**Comment by APBashara** [comment]
Controls has said that they will spec the K type thermocouples as they have to fit in the brake pads correctly. They will have standard two prong connectors on them. We will have to convert from that to an analog out signal using thermocouple amps. They said that they only need two.
