### ISSUE TITLE
Order PCBs

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#16]
Order the PCBs from the PCB Manufactuer

**Comment by APBashara** [comment]
Waiting on sponsor info
https://www.pcbway.com/project/sponsor/Cyclone_Racing_CR_28_071546a3.html

**Comment by APBashara** [comment]
PCB Way gave us $20 for our first order

**Comment by APBashara** [comment]
Just PCB -- $80.86
Stencil -- $10
Shipping -- $25.90
Total -- $116.76

Total with Full Assembly -- $163.76

**Comment by APBashara** [comment]
I think that the best option is to just buy a stencil and do assembly ourselves with the 1316 Coover oven

**Comment by APBashara** [comment]
Had multiple Drill files in the zip, corrected and waiting on approval from PCBWay

Jade said that she is donating money and would help cover the cost for PCBs

**Comment by APBashara** [comment]
A Few issues with the board Design, Closing until they are fixed

**Comment by clairejhaas** [comment]
Created new workspace for this semester. SD card and analog stuff updated this weekend

**Comment by APBashara** [comment]
PCBs will be ordered by end of the week
Have a sponsor
Will have to pay for stencils
