### ISSUE TITLE
SD Card Reader

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#22]
Add SD Card Reader
SPI Based

**Comment by clairejhaas** [comment]
We are doing Micro SD card I'm assuming?

**Comment by APBashara** [comment]
Yes, I think that it will be a good thing to have so that we can log locally

**Comment by clairejhaas** [comment]
https://www.onsemi.com/pdf/datasheet/bss138w-d.pdf

**Comment by clairejhaas** [comment]
@APBashara I am using SPI4 on the STM32 CubeIDE. PE2, PE4, PE5, PE6 for the SD card. The NSS will need to be set, I am not sure if it is input or output, but will be used to CS on the microSD. Please reserve these pins

**Comment by clairejhaas** [comment]
https://www.ti.com/lit/ds/symlink/txb0104.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1695249347568&ref_url=https%253A%252F%252Fwww.ti.com%252Fgeneral%252Fdocs%252Fsuppproductinfo.tsp%253FdistId%253D10%2526gotoUrl%253Dhttps%253A%252F%252Fwww.ti.com%252Flit%252Fgpn%252Ftxb0104
https://www.digikey.com/en/products/detail/texas-instruments/TXB0104DR/1629101

**Comment by clairejhaas** [comment]
https://datasheet.ciiva.com/15174/getdatasheetpartid-716154-15174887.pdf?src-supplier=Verical
