### ISSUE TITLE
SD Card Firmware

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#26]
Write Firmware to log data to SD card over SPI bus

**Comment by clairejhaas** [comment]
![Image](https://github.com/Cyclone-Racing/CR28_Telem/assets/50155045/642eeeba-7c9a-4c52-9a87-1dfb4e9fddad)

**Comment by priedieux** [comment]
> ![Image](https://user-images.githubusercontent.com/50155045/271151758-642eeeba-7c9a-4c52-9a87-1dfb4e9fddad.jpg)
Claire, what mode did you set Spi1, 3, and 4, USART 1 & 2, and I2C1? thanks

**Comment by APBashara** [comment]
We will get the ioc file imported into the main CR_28 project at some point. The mode shouldn't matter, as long as the pins are the same.

**Comment by priedieux** [comment]
https://stm32f4-discovery.net/2015/08/hal-library-20-fatfs-for-stm32fxxx/

**Comment by priedieux** [comment]
http://stm32f4-discovery.net/2014/07/library-21-read-sd-card-fatfs-stm32f4xx-devices/

**Comment by priedieux** [comment]
https://01001000.xyz/2020-08-09-Tutorial-STM32CubeIDE-SD-card/

**Comment by APBashara** [comment]
Using FAT Filesystem, figuring out how to interface with that over SPI Bus
Referencing Digikey Videos

**Comment by priedieux** [comment]
https://www.keil.com/pack/doc/CMSIS/Driver/html/group__mci__interface__gr.html


CMSIS driver info
