### ISSUE TITLE
MCU Board Design Rev 1

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#3]
Begin designing a basic MCU board
Breakout pins
Add programming headers
Super basic revision 1

**Comment by APBashara** [comment]
https://docs.arduino.cc/resources/schematics/ABX00063-schematics.pdf

**Comment by clairejhaas** [comment]
@MHurley117 I created a footprint in Altium using the component wizard for the microcontroller LFQP144 package (datasheet pg 263). Please review. Symbol currently has no pin names until we create the pin outs

**Comment by APBashara** [comment]
I want to make sure that we are keeping analog and digital signals as far apart as possible. I read a few articles that talked about a Microcontroller board design that was 4 layers and was Digital - Power - Core - Ground - Analog. I think that this is a good idea and that we should try and implement this. We can add more digital or analog layers if need be on the top/bottom.

**Comment by APBashara** [comment]
Total Sensors List
CAN Bus to ECU
Extra CAN Bus -- may need to use this to communicate with the PDM for logging
Analog -- 4x suspension pots, 2x brake pressure, 1x steering, 4x Thermocouples for brakes
SPI -- 1x IMU
I2C -- 1x As an extra
Digital -- will want to break out at least 4 interrupt pins and some GPIO pins as well, mostly for "Just in case"
UART -- 2x at least, one for Nextion and at least one extra -- will be able to use as LIN bus if need be that way

***These are subject to change slightly but will give us an amazing start for Rev 1

**Comment by clairejhaas** [comment]
Pins named on MCU footprint and symbol. Please notify if remapping pins so I can adjust footprint. Working on schematic and choosing board connectors. Posted important page numbers in MCU datasheet

- Page 59: LQFP 144 Pin-Out
- Page 120: External Capacitors
- Page 150: Crystal Oscillators
- Page 204: PCB schematic
- Page 264: MCU footprint info
[Datasheet](https://www.st.com/resource/en/datasheet/stm32h730zb.pdf)
[Reference Manual](https://www.st.com/resource/en/reference_manual/rm0468-stm32h723733-stm32h725735-and-stm32h730-value-line-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
[Clock Design](https://www.st.com/resource/en/application_note/an2867-oscillator-design-guide-for-stm8afals-stm32-mcus-and-mpus-stmicroelectronics.pdf)

**Comment by clairejhaas** [comment]
We will be using 0805 (2012 metric) for capacitors and resistors as that is the standard for most board assemblies. We should ask the sponsor if they will provide passive components, as many have bulk stock of standard 0.1uf capacitors and various resistors. 

- [x] Need two 2.2uF capacitors for VCAP pins as well as corresponding resistors based on Page 120

[https://resources.altium.com/p/designing-custom-hardware-microcontrollers](https://resources.altium.com/p/designing-custom-hardware-microcontrollers)

**Comment by clairejhaas** [comment]
@MHurley117 Choose a voltage regulator and look at SMPS/LDO mapping

Component selection (minus LDO) is chosen for SMPS as well as capacitors, resistors, and inductors needed for power supply. I drew traces on VDD/VSS pairs, VCAP, VBAT. 

- [x] SMPS Traces
- [x] VDDLDO Traces

**Comment by clairejhaas** [comment]
SMPS and LDO power supply scheme is configured. 

- [x] Configure USB - will use USB-C. 
- [x] Clock oscillator
  - [HSE Oscillator](https://www.digikey.com/en/products/detail/ecs-inc/ecs-80-10-33-chn-tr/12759418)
  - [2 x 12 pF capacitors](https://www.digikey.com/en/products/detail/kemet/C0805C120K5RAC-AUTO/13177624)
  - [LSE Oscillator](https://www.digikey.com/en/products/detail/ecs-inc/ECS-327-9-34B-TR/3927329?s=N4IgTCBcDaIKIGEDKBaAdAZjAdhQThQwBYAhFAFQCUQBdAXyA) 
  - [2 x 10 pF capacitors](https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL21C100CBANNNC/3888219)

Need the Pinout as soon as possible to do traces to connector

**Comment by APBashara** [comment]
Is there a reason that you are choosing USB-B @clairejhaas?

**Comment by clairejhaas** [comment]
[Altium USB-C](https://www.youtube.com/watch?v=t67KcQHhIC4)
- [DFU-USB Pins](https://stackoverflow.com/questions/46205471/activating-dfu-usb-programming-on-stm32f303)
- [DFU-USB STM Sheet](https://www.st.com/resource/en/application_note/an3156-usb-dfu-protocol-used-in-the-stm32-bootloader-stmicroelectronics.pdf)
- [USB-C Connector](https://www.digikey.com/en/products/detail/amphenol-cs-commercial-products/12401610E4-2A/5775519?s=N4IgTCBcDaIIxgCwAY4DY7IKKIMRgEEQBdAXyA)
- [100K Resistor](https://www.digikey.com/en/products/detail/panasonic-electronic-components/ERJ-6ENF1003V/111841)
- [1.5k Resistor](https://www.digikey.com/en/products/detail/panasonic-electronic-components/ERJ-6ENF1501V/111315)
- [2 x 22 Ohm Resistors](https://www.digikey.com/en/products/detail/panasonic-electronic-components/ERJ-6ENF22R0V/1746474)
- ~~[Alternative Reference for Booting: 20 pin JTAG stuff](https://www.st.com/resource/en/user_manual/um1075-stlinkv2-incircuit-debuggerprogrammer-for-stm8-and-stm32-stmicroelectronics.pdf)~~

[Nucleo Board](https://www.st.com/resource/en/schematic_pack/mb1364-h743zi-c01_schematic.pdf)
[Reset Button](https://www.digikey.com/en/products/detail/e-switch/TL3305CF160QG/5816183)

USB-STLink (requires added chip) or USB-DFU? @APBashara

**Comment by clairejhaas** [comment]
[Pushbotton Switch](https://www.digikey.com/en/products/detail/1825910-6/450-1650-ND/1632536?curr=usd&utm_campaign=buynow&utm_medium=aggregator&utm_source=octopart)
ADC Design
- https://www.youtube.com/watch?app=desktop&v=v6fTa6LRJLI

**Comment by clairejhaas** [comment]
Power config is complete, will work on signal traces to Deutsch connectors next

**Comment by clairejhaas** [comment]
Finished routing the board.

Based on @MHurley117 review:
- [x] Change all vias to thru
- [x] Polygon connection should be set to "direct"
- [x] 5V traces all the same width
- [ ] Rotate R2

Cosmetic changes:
- [ ] Add CR logo
- [ ] Create sections in schematic and repin DT connector on sheet

**Comment by APBashara** [comment]
Board design looks great, I have a few things that I would comment on and want @clairejhaas's and @MHurley117's thoughts on

Instead of a switch for the power input, I'd think we should use a jumper instead, less chance of it getting knocked around

Could we maybe move the Power in, I2C, and CAN signals away from the ADC connections? Differential Signals such as CAN and I2C can cause lots of interference with Analog inputs. The Power in is less of an issue but I would like to try and make the most of analog signal integrity if at all possible. 

Finally, at Comp the design judge mentioned not having any right angles, I am unable to find any so good job there. The other thing that was mentioned was having traces come straight out of the pads for things like resistors. I see a few that have traces coming out at 90deg instead of 180. Is this something that we need to address?

Thanks for the great work @clairejhaas and @MHurley117! I can't wait to see this thing.

**Comment by clairejhaas** [comment]
I am not sure about the 90 degree thing, but I am sure @MHurley117 can answer this. If we have an extra 8 dollars/want to buy the D connector, I can move the digital signals @APBashara. There are also planes separating the analog and digital layers

**Comment by clairejhaas** [comment]
@APBashara In case you didn't see in Electrical, PCB is ready to order, you can go in and double check connections if you want. I am going on vacation, so talk to Michael about getting it ready for manufacturing/assembly.

**Comment by APBashara** [comment]
I think that the PCB looks great. Great job on getting it done over the summer. The only thing that it is missing is the LoRa WAN chip. Do we think that Rev 1 should forgo having wireless for the sake of testing earlier? Or should we focus hard on getting the wireless figured out this week?

**Comment by clairejhaas** [comment]
Do we have a particular LoRa WAN chip that @MHurley117 wants us to use? I personally say forgo it to test earlier, I can do by general if we choose the chip by midday Wednesday

**Comment by APBashara** [comment]
We don't have a specific one picked out yet. That was going to be goal #1 for workday this week. We can talk about it during the meeting this week.

**Comment by clairejhaas** [comment]
- [ ] ADC
- [ ] rpack
- [ ] LoRaWan

General

- [ ] Component Library
- [ ] Standard practices doc (naming conventions)
- [ ] Schematic template
- [ ] Outjobs

**Comment by clairejhaas** [comment]
[CycloneRacing.zip](https://github.com/Cyclone-Racing/CR28_Telem/files/12883204/CycloneRacing.zip)

1 oz copper. Stencil is a GTP file per requested
