### ISSUE TITLE
LoRa Firmware

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#34]
Write Firmware for the LoRa WAN transiver

**Comment by APBashara** [comment]
Send Data, focus on size efficiency and data management

**Comment by APBashara** [comment]
[Possible Library](https://github.com/jgromes/RadioLib)

**Comment by clairejhaas** [comment]
Will be using SPI Bus 3 on STM32, PC10, PC11, PA15, PB2. NSS pin set active low with pull down resistor

**Comment by APBashara** [comment]
[LoRa Driver Example](https://os.mbed.com/teams/Semtech/code/SX126xDevKit//file/c3ab10127815/Demo/DemoApplication.cpp/)

**Comment by APBashara** [comment]
[LoRa HAL](https://github.com/Lora-net/sx126x_driver)
