### ISSUE TITLE
Select Wireless Standard

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#5]
Research RF standards and select new standard for Wireless communication
LoRa research or something similar
Once selected next step will be to start hardware design

**Comment by APBashara** [comment]
Solar Car uses Cellular

**Comment by APBashara** [comment]
MBed has LoRa examples

**Comment by APBashara** [comment]
Find the range and bandwidth of different wireless standards
32 variables at 4 bytes each --> 128 bytes
Need to send multiple times a second

**Comment by APBashara** [comment]
@MHurley117 Lets try and have this done by this weekend so we can figure out what Hardware and Firmware requirements we will need

**Comment by MHurley117** [comment]
Some LoRa chips, will update when I find the rest of the information I dug up. https://docs.google.com/spreadsheets/d/1zFeRqRrq9IaZoFV84xYylSsXO_0kYVbE5QkeqMOAV70/edit?usp=sharing

**Comment by APBashara** [comment]
We will be using LoRa Wan
