### ISSUE TITLE
Spec Board Connectors

### ISSUE THREAD

**Issue by APBashara** [Cyclone-Racing/CR28_Telem#9]
Need to find board to wire connectors for our main harness

**Comment by APBashara** [comment]
Possibility for TE Autosport connectors
I think we should try and stick with TE stuff to keep it consistent across the car

**Comment by APBashara** [comment]
Really nice expensive ones Chris is trying to get sponsored
https://www.te.com/usa-en/industries/autosport/as-connectors-ranges.html

Other Solid option
https://www.te.com/usa-en/product-CAT-D799-H342.html

General Wire to Board list from TE
https://www.te.com/usa-en/plp/wire-to-board-connectors/Y30o9.html

**Comment by clairejhaas** [comment]
Here is a connector that provides right angle, non-panel connection at around $23:

[https://www.te.com/usa-en/product-344108-1.html](https://www.te.com/usa-en/product-344108-1.html)

The associated housing ($8) and necessary pins ($0.40 each): 
[https://www.te.com/usa-en/product-344111-1.html](https://www.te.com/usa-en/product-344111-1.html)
[https://www.te.com/usa-en/product-344113-1.html](https://www.te.com/usa-en/product-344113-1.html)

**Comment by clairejhaas** [comment]
$5 [https://www.te.com/usa-en/product-DT06-12SC-P012.html?compatible=DT13-48PABCD-R015](https://www.te.com/usa-en/product-DT06-12SC-P012.html?compatible=DT13-48PABCD-R015) 
$35 [https://www.te.com/usa-en/product-Dt13-48PABCD-R015.html](https://www.te.com/usa-en/product-Dt13-48PABCD-R015.html)
$4 [https://www.te.com/usa-en/product-DT06-12SA-P012.html?compatible=DT13-48PABCD-R015](https://www.te.com/usa-en/product-DT06-12SA-P012.html?compatible=DT13-48PABCD-R015)
$4 [https://www.te.com/usa-en/product-DT06-12SB-P012.html?compatible=DT13-48PABCD-R015](https://www.te.com/usa-en/product-DT06-12SB-P012.html?compatible=DT13-48PABCD-R015)

**Comment by APBashara** [comment]
Data sheet for board to wire
https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Specification+Or+Standard%7F114-151046%7FA%7Fpdf%7FEnglish%7FENG_SS_114-151046_A.pdf%7FDT13-48PABCD-R015

**Comment by APBashara** [comment]
Total Pin Count as of Right Now
CAN -- 4
Suspension Pots -- 4
Brake Pressure -- 2 
Brake Temp -- 8
IMU -- Max 3
GPS -- Max 3
Power -- 1
GND -- 1
UART for dash -- 2

28 pins max

Will want to spec for more than that most likely
Would be nice to have headers that work with our existing connectors but doesn't seem likely

**Comment by APBashara** [comment]
Having spent some time thinking about what pins we will need and exploring TE's options, I think that the above links in [this message](https://github.com/Cyclone-Racing/CR28_Telem/issues/9#issuecomment-1642883196) is the best option. It will give us lots of flexibility and allow us to have keyed connectors so no one accidentally plugs in the wrong connector. My only concern is the size of it relative to the PCB. Do we have any estimates as to how big we think our PCB will be?

**Comment by clairejhaas** [comment]
The PCB will for sure have to be 5.75" long assuming we choose this connector. I am not entirely sure, but I plan on making the microcontroller more of a rectangle if we go this route, trying to keep it under 3.5" wide
